[package]
name = "yamc"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glutin = "*"
gl = "0.14.0"
thiserror = "1.0.30"